#!/usr/bin/env sh
# primeloader's X init script
# ------------------------------------------------------------------------------

# The MIT License (MIT)
# 
# Copyright (c) 2014 Florian R. A. Angermeier
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

NL="
"

XRANDR_PATH=$(command -v xrandr)
printf "'${XRANDR_PATH}'${NL}"
if [[ -n "${XRANDR_PATH}" ]]; then
	XRANDR_OUTPUT=$(xrandr --listproviders | tr "[:upper:]" "[:lower:]")

	if [[ -z "${VIDEO_CARD_VENDOR_INTEGRATED}" ]]; then
		if [[ "${XRANDR_OUTPUT}" == *intel* ]]; then
			VIDEO_CARD_VENDOR_INTEGRATED="intel"
		fi
	fi

	if [[ -z "${VIDEO_CARD_VENDOR_DISCRETE}" ]]; then
		if [[ "${XRANDR_OUTPUT}" == *nouveau* ]]; then
			VIDEO_CARD_VENDOR_DISCRETE="nouveau"
		elif [[ "${XRANDR_OUTPUT}" == *nvidia* ]]; then
			VIDEO_CARD_VENDOR_DISCRETE="nvidia"
		elif [[ "${XRANDR_OUTPUT}" == *radeon* ]]; then
			VIDEO_CARD_VENDOR_DISCRETE="radeon"
		fi
	fi

	printf "Video card provider (integrated): ${VIDEO_CARD_VENDOR_INTEGRATED}${NL}"
	printf "Video card provider (discrete): ${VIDEO_CARD_VENDOR_DISCRETE}${NL}"

	if [[ -n "${VIDEO_CARD_VENDOR_INTEGRATED}" && -n "${VIDEO_CARD_VENDOR_DISCRETE}" ]]; then
		primeloader-set-provider-offload-sink.sh ${VIDEO_CARD_VENDOR_DISCRETE} ${VIDEO_CARD_VENDOR_INTEGRATED}
	else
		exit -2
	fi
else
	printf "xrandr was not found!${NL}"
	exit -1
fi
